[config]
reload_apps = true

[config.reload_apps_list]
kitty = true

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-matugen.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.gnome-shell]
input_path = '~/.config/matugen/templates/gnome-shell.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/gnome-shell.css'
#post_hook = "dconf write /org/gnome/shell/extensions/user-theme/name \"'default'\" && dconf write /org/gnome/shell/extensions/user-theme/name \"'Material-Gnome'\""

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/.cache/matugen/obsidian-matugen.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
