--color=fg:#e6e3d5
--color=bg:#14140c
--color=hl:#cccb76
--color=fg+:#e6e3d5
--color=bg+:#2b2a22
--color=hl+:#cac8a4
--color=info:#cac8a4
--color=border:#939181
--color=prompt:#cccb76
--color=pointer:#a4d0bc
--color=marker:#a4d0bc
--color=spinner:#cac8a4
--color=header:#a4d0bc
--color=gutter:#14140c
--color=query:#e6e3d5
--color=disabled:#48473a
--color=separator:#939181
--color=scrollbar:#939181
--color=preview-fg:#e6e3d5
--color=preview-bg:#14140c
--color=preview-border:#939181
