alias ..='cd ..'
alias ls="eza -a --icons=always"
alias ll="eza -al --icons=always"
alias lt="eza -a --tree --level=1 --icons=always"
alias shutdown="systemctl poweroff"
alias gmain="gnuke && git switch main && git pull"
alias gmaster="gnuke && git switch master && git pull"
alias ff="fastfetch"
alias bat="batcat"
alias cat="bat"
